name: Production deployment

on:
    push:
      branches:
        - main  
  
jobs:
    live-job:
      environment: Live
      runs-on: ubuntu-latest
      steps:
        - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY